#
# profile file to autorun X
# used by bash and zsh

# ibus
export IBUS_ENABLE_SYNC_MODE=1
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus

if [[ -z "$DISPLAY" ]] && [[ "$XDG_VTNR" == "1" ]]; then
    startx #-- vt$((XDG_VTNR+6))
fi


# Local Variables:
# mode: shell-script
# End:
