#
# profile file to autorun X
# used by bash and zsh

list=`pgrep -U $USER X`
if [[ "$list" == "" ]] && [[ "$XDG_VTNR" == "1" ]]; then
    startx > ~/.xlog
#elif [[ -f ~/.bashrc ]]; then
#    source ~/.bashrc
fi
