#!/bin/bash

# * HISTORY FILE

HISTSIZE=10000
HISTFILESIZE=10000
HISTCONTROL=ignoredups:ignorespace
shopt -s histappend

## check the window size after each command and, if necessary,
## update the values of LINES and COLUMNS.
# shopt -s checkwinsize


# * ALIAS
## Something from oh-my-zsh for bash

alias ls='ls --color=tty'
alias pu='pushd'
alias po='popd'
alias ...='cd ../..'
alias _='sudo -E '


# * CONFIG

source ~/.shellrc  # unified common config for zsh and bash
