#!/bin/bash

## HISTORY FILE
HISTSIZE=10000
HISTFILESIZE=10000
HISTCONTROL=ignoredups:ignorespace
#shopt -s histappend

## check the window size after each command and, if necessary,
## update the values of LINES and COLUMNS.
# shopt -s checkwinsize

## auto cd, like zsh
shopt -s autocd

## Something from oh-my-zsh for bash
alias ls='ls --color=tty'
alias pu='pushd'
alias po='popd'
alias ...='cd ../..'
alias _='sudo -E '

## calling the unified zsh/bash configs
source ~/.shellrc

## bash specific config
if [[ -d ~/.bashrc.d ]]; then
    for f in ~/.bashrc.d/*; do
       [ -f "$f" ] || continue
        # echo $f # for debugging
        source "$f"
    done
    unset f
fi
