#!/bin/zsh


# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh # oh-my-zsh config

# Use another customization directory
ZSH_CUSTOM=$HOME/Documents/my-config/shell/oh-my-zsh


# Look in /path/to/oh-my-zsh/themes/
# "random", will load a random theme each time
ZSH_THEME="rho"

DISABLE_AUTO_UPDATE="true"

plugins=(git colored-man-pages zsh-syntax-highlighting ipinfo)

set -k  # INTERACTIVE_COMMENTS allow to add comments

# Navigation bindings
## See man zshzle for bindkey
## Do cat<RET> to see any-new keybindings
bindkey -s '^[[1;5A' '^Ucd ..^M'  # C-up
bindkey -s '^[[1;5B' '^Ucd -^M'   # C-down
bindkey -s '\ei' '$(!!)^M'        # Get last command output hackish edition

source $ZSH/oh-my-zsh.sh
source ~/.shellrc  # unified shell config

# Local Variables:
# mode: Shell-Script
# sh-indentation: 4
# indent-tabs-mode: nil
# sh-basic-offset: 4
# End:
