firefox:
	echo "GTK_THEME=Adwaita:light /usr/bin/firefox --new-instance $@" > /usr/local/bin/firefox
	chmod +x /usr/local/bin/firefox

gitg:
	echo "GTK_THEME=Adwaita:light /usr/bin/gitg $@" > /usr/local/bin/gitg
	chmod +x /usr/local/bin/gitg
