#+TITLE: systemd
#+DATE: Wednesday, Mar 02 2016


systemctl --failed
systemd-analyze blame

* sudo

  alterative to su

  machinectl shell --uid=root

* separted /var partition


  The problem is journald Or rather how it is still logging to /var
  while systemd is trying to unmount it. Solutions there are two ways
  to go about it:

** volatile location

   Make journald log to a volatile location in /run so it doesn't lock
   /var, but the tradeoff is that you lose logs at shutdown.

   CHANGE /etc/systemd/journald.conf

   Storage=volatile

** shutdown hook

   Or set up a shutdown hook to unmount /var later. This won't remove
   the failed message as systemd will still try to unmount /var but
   will indeed unmount /var properly at the end of the shutdown
   sequence. You just won't see it. (I haven't tested that solution
   though)

   Add a shutdown hook to mkinitcpio's HOOKS= array, e.g. :

   HOOKS="base udev autodetect block keymap encrypt lvm2 filesystems usbinput fsck var shutdown"

* Enable getty

  #+BEGIN_SRC bash
    systemctl enable getty@tty1.service
  #+END_SRC

* Disable Clearing of Boot Messages
  based on: [[https://wiki.archlinux.org/index.php/Systemd_FAQ#How_do_I_get_more_verbose_output_during_boot.3F][Arch Wiki]]

  After the boot process, the screen is cleared and the login prompt
  appears, leaving users unable to read init output and error
  messages.

** change in source

   #+BEGIN_SRC bash
     sed '/TTYVTDisallocate=/s/yes/no/' /usr/lib/systemd/system/getty@.service
   #+END_SRC

** using override

   systemd enable only support symlink since mid 2017 (too me long to
   realize don't know exact date, was saved by reserved VT) so
   override is better method since, source will be reset when systemd
   updates.

   #+BEGIN_SRC bash
     cat << EOF > /etc/systemd/system/getty@tty1.service.d/noclear.conf
     [Service]
     TTYVTDisallocate=no
     EOF
   #+END_SRC

* Autologin
  based on: [[https://wiki.archlinux.org/index.php/getty][Arch Wiki]]

  #+BEGIN_SRC bash
    cat << EOF > /etc/systemd/system/getty@tty1.service.d/override.conf
    [Service]
    ExecStart=
    ExecStart=-/usr/bin/agetty --autologin $USER --noclear %I $TERM
    EOF
  #+END_SRC

* Using systemd --user
  based on: [[https://wiki.archlinux.org/index.php/Systemd/User][Arch Wiki]], [[https://bitbucket.org/KaiSforza/systemd-user-units][KaiSforza's Guide]]

  Using =systemctl --system= to do anything requires *root* privileges
  and is therefore not useful to unprivileged users.

* slice

  # /etc/systemd/system/limit-512M.slice

  #+BEGIN_EXAMPLE
    [Unit]
    Description=Slice with MemoryLimit=512M
    Before=slices.target

    [Slice]
    MemoryAccounting=true
    MemoryLimit=512M
  #+END_EXAMPLE


  then you can run program in that slice and memory accounting will be
  enabled:

  systemd-run --slice limit512M --scope google-chrome-stable

* REFERENCE

  - https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
