#!/usr/bin/env bash

function tmux {
    sessions=$(/usr/bin/tmux list-session 2> /dev/null)
    if [[ "$sessions" == "" ]]; then
        /usr/bin/tmux $@
        return
    fi

    # TODO: handel attach if its sent
    /usr/bin/tmux a $@
}
