firefox:
	echo 'GTK_THEME=Adwaita:light exec /usr/bin/firefox $$@' > /usr/local/bin/firefox
	chmod +x /usr/local/bin/firefox

gitg:
	echo 'GTK_THEME=Adwaita:light exec /usr/bin/gitg $$@' > /usr/local/bin/gitg
	chmod +x /usr/local/bin/gitg

chromedriver:
	echo 'exec /usr/bin/chromium $$@' > /usr/local/bin/chromedriver
	chmod +x /usr/local/bin/chromedriver
