#+TITLE: X
#+DATE: 2017 Aug 23, Wednesday


* sessions

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    # ALT + CTRL + Function key (F1-F6)
    xinit -- :1
    ssh -X <username>@<ip>
    gnome-session
  #+END_SRC

  The Display number is typically something like :0 or :1, which mean
  "the first X11 display on the local machine" and "the second X11
  display on the local machine" respectively. The display is stored in
  the environment variable DISPLAY, and any X11 application uses this
  variable to determine how to contact the X11 server and show its
  windows when it starts up.

  If your X11 server is listening on the network, then people can
  contact it from outside your computer. The first display :0 lives on
  port 6000, the second on 6001, etc:

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    netstat -natp | grep :600
    nmap localhost
  #+END_SRC


  virtual console 8

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    xinit -- :1 vt8
  #+END_SRC


* setxkbmap

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    setxkbmap -option compose:caps
  #+END_SRC

  If you cannot live without CapsLock a different key can be used. See
  /usr/share/X11/xkb/rules/base.lst file for other key names.

  setxkbmap -option grp:switch,grp:shift_toggle,grp_led:scroll us,lt

* x2x

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    ssh <username>@<hostname> -X x2x -to :0 -from west
  #+END_SRC

* xrandr stuff

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    xrandr -q | grep -w Screen
    xrandr --verbose | grep *current
  #+END_SRC

* Screen Shot

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    DISPLAY=:0 import -window root <path>
    scrot
  #+END_SRC

* xwd

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    xwd -root -display :0.0| xwdtopnm | pnmtopng > Screenshot.png
  #+END_SRC

* input

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    xinput list
  #+END_SRC

* compose key list

  #+HEADER: :results output :eval no-export
  #+BEGIN_SRC sh :exports both
    less /usr/share/X11/locale/${LANG/utf/UTF-}/Compose
  #+END_SRC

* Xresources

  Xresources loaded when X server is started.

  to manully reload Xresources

  $ xrdb ~/.Xresources #


  Load a resource file, and merge with the current settings:

  $ xrdb -merge ~/.Xresources
