#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

## some idiotic xorg settings
#setxkbmap -layout "dvorak, us" -option "grp:ralt_rshift_toggle,grp_led:caps,compose:caps"

case $1 in
    none) exec xterm;;
    gnome) exec gnome-session;;
    kde) exec startkde;;
    box) exec openbox-session;;
    xfce);;
    *) exec startxfce4;;
esac
