#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [[ -f "$f" ]] && source "$f"
    done
    unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

case $1 in
    none) exec xterm;;
    gnome) exec gnome-session;;
    kde) exec startkde;;
    box) exec openbox-session;;
    xfce) exec startxfce4;;
    *) exec startxfce4;;
esac
