# https://docs.astral.sh/ruff/rules/

target-version = 'py312'  # minimum version to target
indent-width = 4
line-length = 75

builtins = ['_']
extend-exclude = [
    '.vscode',
]


[format]  # usless as black
docstring-code-format = true
indent-style = 'space'
line-ending = 'lf'
quote-style = 'single'
skip-magic-trailing-comma = false


[lint.flake8-quotes]
inline-quotes = 'single'


[lint.flake8-import-conventions.extend-aliases]
'datetime' = 'dt'


[lint.isort]
force-single-line = true  # Forces all from imports to appear on their own line.
length-sort-straight = true
lines-after-imports = 2
lines-between-types = 1  # Use a single line between direct and from import.


[lint]
extend-select = [  # default [ 'E4', 'E7', 'E9', 'F' ]
    'YTT',         # flake8-2020
    'S',           # flake8-bandit
    'COM',         # flake8-commas
    'C4',          # flake8-comprehensions
    'ICN',         # flake8-import-conventions
    'Q',           # flake8-quote
    'RET',         # flake8-return
    'SIM',         # flake8-simplify
    'I',           # isort
    'C90',         # mccabe
    'N',           # pep8-naming
    'E',           # pycodestyle
    'PGH',         # pygrep-hooks
    'PL',          # pylint
    'UP',          # pyupgrade
]

ignore = [
    'S101',        # flake8-bandit.assert

    'RET502',      # flake8-return.implicit-return-value
    'RET503',      # flake8-return.implicit-return

    'Q003',        # flake8-quote.avoidable-escaped-quote

    'SIM300',      # flake8-simplify.yoda-conditions
    'SIM102',      # flake8-simplify.collapsible-if

    'I001',        # isort.unsorted-imports

    'N802',        # pep8-naming.invalid-function-name
    'N803',        # pep8-naming.invalid-argument-name
    'N806',        # pep8-naming.non-lowercase-variable-in-function
    'N815',        # pep8-naming.mixed-case-variable-in-class-scope
    'N816',        # pep8-naming.mixed-case-variable-in-global-scope

    'E701',        # pycodestyle.multiple-statements-on-one-line-colon

    'PLR0911',     # pylint.too-many-return-statements
    'PLR2004',     # pylint.magic-value-comparison

    'UP032',       # pyupgrade.f-string : prefer f-string over format
]
